### ISSUE TITLE
API Response 404

### ISSUE THREAD

**Issue by JoshLiCoding** [Garrett-Freddo/kanban-api#1]
Hello,

Sorry for creating an issue. I have followed the README.md for setting up the API locally - with ".env" file containing "CONNECTION_STRING="mongodb://localhost:27017" in root directory and mongodb-community@4.4 running.
However, the server returns "Cannot GET /tasks" when tested by manually changing the URL to "http://localhost:9000/tasks":
![image](https://user-images.githubusercontent.com/43073270/122629809-bf193b00-d08d-11eb-9700-bc45bbbb5154.png)
![image](https://user-images.githubusercontent.com/43073270/122629813-c6404900-d08d-11eb-9a3f-946f471a3978.png)
In addition, when accessed through the Fetch API or XMLHttpRequest on React, passing JSON data as parameters, the PUT/POST routes throw 404 errors as well (no matter the URL path):
(Fetch API)
![image](https://user-images.githubusercontent.com/43073270/122629904-2636ef80-d08e-11eb-864f-9c04775c98c7.png)
![image](https://user-images.githubusercontent.com/43073270/122630354-ea515980-d090-11eb-8498-30e3b13e5f06.png)
(XMLHttpRequest)
![image](https://user-images.githubusercontent.com/43073270/122629779-7792af00-d08d-11eb-832d-12140089b5e4.png)
![image](https://user-images.githubusercontent.com/43073270/122630365-03f2a100-d091-11eb-8581-8d55159ebdf2.png)
(console output for both manual and React)
![image](https://user-images.githubusercontent.com/43073270/122630124-a873e380-d08f-11eb-8ef2-bf0fe68e4941.png)
![image](https://user-images.githubusercontent.com/43073270/122629980-a5c4be80-d08e-11eb-85a0-c8d4c6eb1845.png)
![image](https://user-images.githubusercontent.com/43073270/122629983-aa897280-d08e-11eb-9b5d-cfccfd6ca71d.png)
I am unsure whether this is caused by problems in 1) setting up Kanban API locally 2) Express.js routing or 3) passing the object type - e.g. JSON, Scheme, encoded URL text. Since I am unfamiliar with the technologies in use, I have attempted to resolve this problem independently for a few hours through researching online - although to no avail. Clarifications on this issue would be greatly appreciated.

Thank you,
Joshua Li

**Comment by Garrett-Freddo** [comment]
This is my bad, try connecting to http://localhost:9000/v1/<endpoint> , that should work better. Thank you for pointing this out! 
![image](https://user-images.githubusercontent.com/65565481/122631151-0fdd6380-d08f-11eb-9254-fe6b4aede5fe.png)
